server:
  port: 8083

spring:
  application:
    name: task-event-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/task-event?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.angeldevs.taskeventservices.shared.infrastructure.persistence.jpa.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:9090}
        instance:
          service-base-url: ${SERVICE_URL:http://localhost:8083}

documentation:
  application:
    description: "@project.description@"
    version: "@project.version@"

authorization:
  jwt:
    secret: 14db3b405fd39d8a7434ea25d19e80eba402da04a4807ffa95114e92a140dd1c
    expiration:
      days: 7

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_HOST:localhost}    
    non-secure-port-enabled: false
    secure-port-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
